=== ReaperKoji/bughunter/examples/scope.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HunterOps Scope",
  "type": "object",
  "required": ["targets", "authorized_by", "valid_from", "valid_to", "rules_of_engagement", "signature_meta", "signature"],
  "properties": {
    "targets": {
      "type": "array",
      "items": {"type": "string"}
    },
    "authorized_by": {"type": "string"},
    "valid_from": {"type": "string"},
    "valid_to": {"type": "string"},
    "rules_of_engagement": {"type": "string"},
    "signature_meta": {
      "type": "object",
      "properties": {
        "algorithm": {"type": "string"},
        "created_at": {"type": "string"}
      },
      "required": ["algorithm"]
    },
    "signature": {"type": "string"}
  }
}

=== ReaperKoji/bughunter/examples/scope_signed.json
{
  "targets": [
    "localhost",
    "127.0.0.1",
    "*.example.com"
  ],
  "authorized_by": "Security Team",
  "valid_from": "2026-03-10T00:00:00Z",
  "valid_to": "2026-04-10T00:00:00Z",
  "rules_of_engagement": "Automated scanning is permitted under rate limits.",
  "signature_meta": {
    "algorithm": "rsa-sha256",
    "created_at": "2026-03-10T14:06:18.781126Z"
  },
  "signature": "LlMxksexbb3Yi6HWfT1+MybFvkRUDbJmQ1A6DGeWjvOPR6fC0bZa2RgiR6yHBTJsiSRkl6Zn84Vwai5ZCPJZsutKQB0Or67nRmnpW6wdEYcahOM9hK6DBcsGNwZUCpNjcCHeBXAqKYxonzWDhGTWTsY1DX6l1Fm2lrTF5W9cFrVMlt870ZCKJudteUfkcpMBLQ7tY596P3n7M7L3OOI7XXzwTbgJF8O034uKCTjeDR01f+PgQR9ulLPKr77s2fSmNl0X95Kt0rDTiuZpwGjmmzqVXXCQsaIHVi0iIR1VTuD3EfPE9JxLK9NrKPySSUegmBf3rXyFVcDr/2cImx9Zlg=="
}
